{% set name = "mimalloc" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/mimalloc/archive/v{{ version }}.tar.gz
  sha256: a4bf4e1e0764230e8abbcec88e2ffaf170804fdfcda15e6a17f63f7088d8e692
  patches:
    - 0001-update-install-path-patch.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

# .
# ├── include
# │  ├── mimalloc-new-delete.h
# │  ├── mimalloc-override.h
# │  └── mimalloc.h
# └── lib
#    ├── libmimalloc.a
#    ├── libmimalloc.so -> libmimalloc.so.1.6
#    ├── libmimalloc.so.1.6
#    └── mimalloc.o

test:
  commands:
    - test -f $PREFIX/lib/libmimalloc${SHLIB_EXT}
    - test -f $PREFIX/include/mimalloc.h

about:
  home: https://github.com/microsoft/mimalloc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: mimalloc is a compact general purpose allocator with excellent performance.

  description: |
    mimalloc (pronounced "me-malloc") is a general purpose allocator with
    excellent performance characteristics. Initially developed by Daan Leijen
    for the run-time systems of the Koka and Lean languages.
  dev_url: https://github.com/microsoft/mimalloc

extra:
  recipe-maintainers:
    - elbaro
    - xhochy
