{% set name = "mimalloc" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/mimalloc/archive/v{{ version }}.tar.gz
  sha256: 2b1bff6f717f9725c70bf8d79e4786da13de8a270059e4ba0bdd262ae7be46eb

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("mimalloc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

# .
# ├── include
# │  ├── mimalloc-new-delete.h
# │  ├── mimalloc-override.h
# │  └── mimalloc.h
# └── lib
#    ├── libmimalloc.a
#    ├── libmimalloc.so -> libmimalloc.so.1.6
#    ├── libmimalloc.so.1.6
#    └── mimalloc.o

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test.c
  commands:
    - test -f $PREFIX/lib/libmimalloc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/mimalloc.h           # [unix]
    - grep -vr feedstock_root $PREFIX/lib/cmake    # [unix]
    - if not exist %LIBRARY_PREFIX%\\lib\\mimalloc.dll exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\mimalloc.lib exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\mimalloc.h exit 1  # [win]
    - $CC -L$PREFIX/lib -lmimalloc -I$PREFIX/include test.c -o test  # [unix]
    - LD_LIBRARY_PATH=$PREFIX/lib ./test  # [unix]

about:
  home: https://github.com/microsoft/mimalloc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: mimalloc is a compact general purpose allocator with excellent performance.

  description: |
    mimalloc (pronounced "me-malloc") is a general purpose allocator with
    excellent performance characteristics. Initially developed by Daan Leijen
    for the run-time systems of the Koka and Lean languages.
  dev_url: https://github.com/microsoft/mimalloc

extra:
  recipe-maintainers:
    - elbaro
    - xhochy
