{% set name = "mimalloc" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/mimalloc/archive/v{{ version }}.tar.gz
    sha256: 0eed39319f139afde8515010ff59baf24de9e47ea316a315398e8027d198202d
  - url: https://github.com/microsoft/mimalloc/raw/v{{ version }}/bin/mimalloc-redirect.lib  # [win]
    sha256: f23cf5204b77cb899da096a0eb8e1e7c980b6639118ea36a139a20f30dc02d59  # [win]
    folder: bin  # [win]
  - url: https://github.com/microsoft/mimalloc/raw/v{{ version }}/bin/mimalloc-redirect.dll  # [win]
    sha256: 63dc4f158fd76940ec018b42f83d92d8ceec70043b1ac2a8455fb0d67e1feebf  # [win]
    folder: bin  # [win]

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("mimalloc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - test.c
  commands:
    - test -f $PREFIX/lib/libmimalloc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/mimalloc.h           # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\mimalloc.dll exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\mimalloc.lib exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\mimalloc.h exit 1  # [win]
    - $CC $CFLAGS $LDFLAGS test.c -lmimalloc -o test  # [unix]
    - LD_LIBRARY_PATH=$PREFIX/lib ./test  # [unix]

about:
  home: https://github.com/microsoft/mimalloc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: mimalloc is a compact general purpose allocator with excellent performance.

  description: |
    mimalloc (pronounced "me-malloc") is a general purpose allocator with
    excellent performance characteristics. Initially developed by Daan Leijen
    for the run-time systems of the Koka and Lean languages.
  dev_url: https://github.com/microsoft/mimalloc

extra:
  recipe-maintainers:
    - elbaro
    - xhochy
